### PR TITLE
updated the visualiser to show colour depending on direction of motion

### PR DESCRIPTION
**Pull request by PDuckworth**
This is important to visulize the learnt clusters.

### CODE REVIEW

**Comment by kunzel** [comment]
Hi @PDuckworth, instead of replacing the 'old' method of visualizing trajectories, can you please add you new method along the first one. This way we could build up a library of visualizing trajectories for different purposes...

**Comment by PDuckworth** [comment]
@kunzel @hawesie 
I changed the message type to include an "vis_option" string. Now can show either random colours or direction based colours, red-blue or red_green.

**Comment by marc-hanheide** [comment]
This looks very outdated, folks?

**Comment by kunzel** [comment]
@PDuckworth given more recent developments, can we close this PR?

**Comment by PDuckworth** [comment]
This is very old. Although, is there a different way to visualise the trajectory using colours?

**Pull request closed without merging**
