### PR TITLE
add initial version of soma_pcl_segmentation (object search demo)

### PR DESCRIPTION
**Pull request by kunzel**

### CODE REVIEW

**Comment by kunzel** [comment]
This PR includes modules for the y2 review demo. 

@hawesie this also inserts objects/rois in the geospatial store when missing.

**Comment by hawesie** [comment]
`KeyError: 'semantic_map_publisher'` (i.e. missing dependency)

**Comment by kunzel** [comment]
semantic_map_publisher is listed in the package.xml of soma_pcl_segmentation. Should it go somewhere else? Does it require a dependency to strands_3D_mapping? And is it a problem, that semantic_segmentation is private?

**Comment by kunzel** [comment]
close for now as not all dependencies are public yet...

**Comment by cburbridge** [comment]
Are these changes important before I start merging in world_state stuff in the way we discussed last week?

**Comment by kunzel** [comment]
No.

**Pull request closed without merging**
