### PR TITLE
soma geospatial store updates.

### PR DESCRIPTION
**Pull request by PDuckworth**

### CODE REVIEW

**Comment by kunzel** [comment]
Please merge

**Comment by PDuckworth** [comment]
@Kunzel Please note that I am updating a field in the geospatial soma store. For documents with a `soma_roi_id`, I add a region score. Which is essentially the number of seconds the robot has been looking at that region. I hope that's OK. It's implemented from `trajectory_behaviours`.

**Comment by kunzel** [comment]
@PDuckworth hmm, but not in this code here? I'd say that this should go somewhere else, as it is related to the robot experience over time and not to the region as such. I think it would be better if you have observations or resulting scores from those in a separate collection of robot experiences where you can obviously refer to the ID of the roi.  
If its too complicated to change it for the deployment, leave it for now. We can deal with it afterwards.

**Comment by PDuckworth** [comment]
@kunzel I agree. I actually wrote the above message, and then thought it was a bad idea to mess about with geo store. I should have edited the message (sorry). 

I use the roi's from the geo store, but create a `region_knowledge` store which just saves the number of times the robot has been to a roi, and also a histogram of number of times per hour. This info is taken from /robot_pose and is already in my code. I just need to test it for the deployment.

**Comment by kunzel** [comment]
@PDuckworth This sounds good to me. I would suggest that you record a history of visits rather then an accumulated number. From such a history you could easily extract the number of visits. But it gives you more options when analysing the data wrt time. Just a thought. However, I guess one could generate a history anyway as we have robot poses over time.

**Comment by PDuckworth** [comment]
I was concerned about storing too much information. i.e. the instances a robot monitored a region could get very large over three weeks. So I just store a count of the robot_pose (1 per second). 

I also store the count per hour . I create a nice graph too, but that is currently not working on bob for some reason.

**Pull request merged**
